#!/bin/bash

# SPDX-FileCopyrightText: Copyright 2025 Siemens
#
# SPDX-License-Identifier: Apache-2.0

# Select files to format
files=$(git diff --cached --name-only | grep -E '\.(c|h)$')
[ -z "$files" ] && exit 0
# Format all relevant lines of selected files
diff=$(git diff --cached -U0 --no-color $files)
echo "$diff" | clang-format-diff -p1 -i
exit 0
